# Generated by Django 3.2.7 on 2022-01-20 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='Внешний ID ПМ')),
                ('name', models.CharField(max_length=256, verbose_name='Имя и фамилия ПМ')),
                ('tg_chat_id', models.PositiveIntegerField(unique=True, verbose_name='Чат id ПМ в Телеграм')),
                ('available_time', models.JSONField(verbose_name='Время cозвонов')),
            ],
            options={
                'verbose_name': 'Проект менеджер',
                'verbose_name_plural': 'Проект менеджеры',
            },
        ),
        migrations.CreateModel(
            name='Student_distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_distribution', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Провести распределение в команды',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='Внешний ID команды')),
                ('name', models.CharField(max_length=256, verbose_name='Имя команды')),
                ('start_time_call', models.TimeField(verbose_name='Время начала созвонов')),
                ('end_time_call', models.TimeField(verbose_name='Время окончания созвона')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='Внешний ID ученика')),
                ('name', models.CharField(max_length=256, verbose_name='Имя и фамилия студента')),
                ('tg_chat_id', models.PositiveIntegerField(unique=True, verbose_name='Чат id ученика в Телеграм')),
                ('status', models.CharField(max_length=256, verbose_name='Статус ученика (джун, новичок+, новичок,)')),
                ('start_time_call', models.TimeField(verbose_name='Время начала созвона')),
                ('end_time_call', models.TimeField(verbose_name='Время окончания созвона')),
                ('is_far_east', models.BooleanField(verbose_name='Дальний Восток')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_automatization_bot.team')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('students', models.JSONField()),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_automatization_bot.project_manager')),
                ('teams', models.ManyToManyField(to='project_automatization_bot.Team')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
