# Generated by Django 3.2.7 on 2022-01-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_automatization_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='week',
            field=models.PositiveIntegerField(choices=[('Третья', 3), ('Четвертая', 4)], null=True, verbose_name='Выбранная неделя занятий'),
        ),
    ]
