# Generated by Django 3.2.7 on 2022-01-22 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_automatization_bot', '0002_student_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_manager',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='end_time_call',
        ),
        migrations.AddField(
            model_name='student',
            name='time_call',
            field=models.JSONField(null=True, verbose_name='JSON формат времени'),
        ),
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_automatization_bot.project_manager'),
        ),
        migrations.AlterField(
            model_name='student',
            name='end_time_call',
            field=models.TimeField(null=True, verbose_name='Удобное время конца созвона'),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_time_call',
            field=models.TimeField(null=True, verbose_name='Удобное время начала созвона'),
        ),
        migrations.AlterField(
            model_name='student',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project_automatization_bot.team'),
        ),
        migrations.AlterField(
            model_name='student',
            name='week',
            field=models.CharField(choices=[('3', '3'), ('4', '4')], max_length=1, null=True, verbose_name='Выбранная неделя занятий'),
        ),
    ]
